### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Jonesckevin** [digitalsleuth/WIN-FOR#1]
I suggest relocating the X-Ways Checkbox to be next to the user data to quickly enable/disable. This would allow users who want everything except X-Ways to more easily identify the checkbox under a subcategory since having it enabled requires user data.

![X-Ways](https://user-images.githubusercontent.com/57996927/232921696-a5a92e55-8320-49ce-9bba-959f2f7b8719.png)

Second suggestion would be to include Everything from Voidtools as this tool can benefit in finding tools or files locally while also doubling other purposes like malware analysis or regex/wildcard file searches on mounted drives.

**Comment by digitalsleuth** [comment]
Hey @Jonesckevin , regarding the X-Ways box movement, it's a good idea. I'll review how this is going to take shape.
As for the Voidtools, I've already added it to the Winrepo, and will give it a shot in the upcoming release.

**Comment by Jonesckevin** [comment]
Sounds good!!

**Comment by digitalsleuth** [comment]
@Jonesckevin RC 12 has been released which addresses the X-Ways suggestion. The display is now dynamic and no longer static, allowing for a live update of available tools.
