### ISSUE TITLE
Program Addition

### ISSUE THREAD

**Issue by Jonesckevin** [digitalsleuth/WIN-FOR#3]
Can you add the Microsoft Store tool into the toolset: MSI Viewer

**Comment by digitalsleuth** [comment]
Hi @Jonesckevin , looks like an interesting tool. I'll see about adding it. Have you also tried lessmsi, which is one of the tools already in the WIN-FOR library?

**Comment by Jonesckevin** [comment]
I have not yet. I will be sure to check it out!

**Comment by digitalsleuth** [comment]
Hi @Jonesckevin , I've added the MSI Viewer tool to the list, and should be available to you in the Customizer now!
