### ISSUE TITLE
Hash mismatch errors on 8.30 in Windows 10 and Windows 11 

### ISSUE THREAD

**Issue by 4NSIK1** [digitalsleuth/WIN-FOR#4]
Hi DigitalSleuth, 
I have been using win-for 8.30 release with success, but today when trying to install it on Win10 or Win11 VirtualBox VM it is having a hash mismatch with the win-for-salt-v2023.26.2.zip - pic attached.  
Is there anything I can do to fix this?
Thanks
Robert
![SCR-20231003-oks](https://github.com/digitalsleuth/WIN-FOR/assets/15110297/4fad7338-c031-4902-869d-0a1f02e1a48c)

**Comment by 4NSIK1** [comment]
Update, after checking the output logs, this might be due to not locating https://repo.saltproject.io/salt/py3/windows/3005/**salt-3005.2-1-windows-amd64.exe** 
![SCR-20231003-pwj](https://github.com/digitalsleuth/WIN-FOR/assets/15110297/d04b378b-b3d6-49d4-8b28-36d721906a48)
It looks like salt-3005.2-1 does not exist but has been replaced with [salt-3005.3-1-windows-amd64.exe](https://repo.saltproject.io/salt/py3/windows/3005/salt-3005.3-1-windows-amd64.exe)

**Comment by 4NSIK1** [comment]
I installed Salt 3005.2.1 manually but the SHA256 mismatch appears to be the issue between the calculated hash and the stored hash.
![SCR-20231004-9up-3](https://github.com/digitalsleuth/WIN-FOR/assets/15110297/10947491-d1f5-4793-8a91-1c6d7e59c99b)

**Comment by digitalsleuth** [comment]
Hi @4NSIK1 , the issue is actually with the release file and not with Saltstack. I'll be issuing a new release of the Salt States this evening which should fix that issue, and encompass many changes. I'll also release a new version of the Win-FOR Customizer in the next day or two which will add some new features.

I'll let you know as soon as the Salt State issue is fixed!

**Comment by 4NSIK1** [comment]
Brilliant, @digitalsleuth thanks so much. I am loving this tool.

**Comment by digitalsleuth** [comment]
Hi @4NSIK1 , I've released a new version, v2023.27.0, which should address this issue, Let me know how it goes.

Cheers!

**Comment by digitalsleuth** [comment]
Hi @4NSIK1 , well the new version had a few bugs, so I've fixed those and released a new one, v2023.27.1. This should fix all the issues.

Cheers!

**Comment by afp235** [comment]
Hi @digitalsleuth, I know you mentioned this has been resolved but I'm getting this same issue with the newest version:

![wfor](https://github.com/digitalsleuth/WIN-FOR/assets/101343139/15bca461-c573-4637-80d5-ebbc97710a69)

Is there anything that I could do to solve this?

**Comment by digitalsleuth** [comment]
Hi @afp235 , this issue should be resolved now. It appears to be an issue with some changes happening on Github's end. I've re-uploaded the current version (with a new version number), and everything should work now.
