### ISSUE TITLE
Add maldump tool to WIN-FOR

### ISSUE THREAD

**Issue by Qynklee** [digitalsleuth/WIN-FOR#7]
I completed WIN-FOR installation and used it in some case Windows forensic. And I findout WIN-FOR doesnt have [maldump](https://github.com/NUKIB/maldump) tool - Tool extract quarantine AV file from partition or image mounted by FTK.

**Comment by digitalsleuth** [comment]
Hi @Qynklee , I'll be taking a look at this shortly, thank you!

**Comment by digitalsleuth** [comment]
Hi @Qynklee , sorry for not replying to this sooner, but I added maldump into Win-FOR about a month ago. Not sure if you've had a chance to take a peek, but it's available. Thanks for the recommendation!
